### PR TITLE
fix: prevent infinite polling

### LINKED ISSUE #202: Status polling does not stop after error
As discussed previously on Discord chat, when there's an error dumpus keeps sending requests indefinitely. I was able to produce this behavior by entering an invalid or expired package link.

image

### PR DESCRIPTION
**Pull request by skdhg**
closes #202

### CODE REVIEW

File: src/app/[locale]/onboarding/loading/page.tsx [hunk 1]
```diff
@@ -66,14 +66,20 @@ export default function Page() {
   const nextID = getNextID(selectedID);
 
   useEffect(() => {
-    if (
+    const isLockedOrErrored =
+      statusQuery.data?.processingStep === "LOCKED" ||
```
Comment (florian-lefebvre) [inline src/app/[locale]/onboarding/loading/page.tsx:70]: @Androz2091 does being LOCKED always mean it's errored?

**Review by florian-lefebvre — COMMENTED** [review]
Thanks for the contribution! I just need a confirmation before we merge. I'll probably make a huge rework of this page because it's quite messy

File: src/app/[locale]/onboarding/loading/page.tsx (hunk 1 above)
Comment (Androz2091) [reply src/app/[locale]/onboarding/loading/page.tsx:70]: No, it means that the processing of the package has not started yet

Comment (florian-lefebvre) [reply src/app/[locale]/onboarding/loading/page.tsx:70]: Tell me what you think but I think we shouldn't disable polling if it's locked because it will prevent us from knowing how the status evolves

Comment (Androz2091) [reply src/app/[locale]/onboarding/loading/page.tsx:70]: Yes, definitely

Comment (florian-lefebvre) [reply src/app/[locale]/onboarding/loading/page.tsx:70]: Nevermind, I am just going to test it locally

File: src/app/[locale]/onboarding/loading/page.tsx [hunk 2]
```diff
@@ -66,14 +66,20 @@ export default function Page() {
...
+      !!statusQuery.data?.isErrored;
```
Comment (florian-lefebvre) [inline src/app/[locale]/onboarding/loading/page.tsx:71]:
```suggestion
    const hasError = !!statusQuery.data?.isErrored;
```

File: src/app/[locale]/onboarding/loading/page.tsx [hunk 3]
```diff
@@ -66,14 +66,20 @@ export default function Page() {
...
+    const isPending =
       statusQuery.data?.processingStep !== "PROCESSED" ||
       !packageLink ||
       !UPNKey ||
-      !processData
-    ) {
+      !processData;
+
+    if (isPending) {
+      isStatusQueryEnabled.current = isLockedOrErrored;
```
Comment (florian-lefebvre) [inline src/app/[locale]/onboarding/loading/page.tsx:79]:
```suggestion
      isStatusQueryEnabled.current = !hasError;
```

**Review by florian-lefebvre — CHANGES_REQUESTED** [review]

**Review by florian-lefebvre — APPROVED** [review]

**Comment by florian-lefebvre** [comment]
Thank you!
